version: '2'
services:
    pkgbuild:
        build:
            context: .
            dockerfile: build/Dockerfile
        volumes: 
            - ./packages/net/hass-tracker:/home/openwrt/sdk/feeds/packages/net/hass-tracker:ro
            - ./build/bin:/home/openwrt/sdk/bin:rw
